#ifndef _REGISTRY_FILTER_H
#define _REGISTRY_FILTER_H

#define _DRIVER_NAME "RegistryFilter"
#define DRIVER_NAME L""##_DRIVER_NAME
#define DRIVER_NAME_WITH_EXT L""##_DRIVER_NAME##".sys"
#define KERNEL_MODE_DRIVER_NAME L"\\\\.\\"##_DRIVER_NAME


#define IOCTL_DO_UPDATE_RULES \
CTL_CODE ( \
  FILE_DEVICE_UNKNOWN, \
  (0x800 + 0), \
  METHOD_BUFFERED, \
  FILE_SPECIAL_ACCESS \
)
#define IOCTL_SET_CREATE_THREAD \
CTL_CODE ( \
  FILE_DEVICE_UNKNOWN, \
  (0x800 + 1), \
  METHOD_BUFFERED, \
  FILE_SPECIAL_ACCESS \
)
#define IOCTL_REMOVE_CREATE_THREAD \
CTL_CODE ( \
  FILE_DEVICE_UNKNOWN, \
  (0x800 + 2), \
  METHOD_BUFFERED, \
  FILE_SPECIAL_ACCESS \
)
#define IOCTL_STOP_SERVICE \
CTL_CODE ( \
  FILE_DEVICE_UNKNOWN, \
  (0x800 + 3), \
  METHOD_BUFFERED, \
  FILE_SPECIAL_ACCESS \
)

typedef struct _DRIVER_IOCTL_OUTPUT {
  int32_t _retVal;
} DRIVER_IOCTL_OUTPUT, *PDRIVER_IOCTL_CONTROL;

#endif // !_REGISTRY_FILTER_H
